copyright: Copyright &copy; 2024 Florian Milc

site_name: My Documentation Website
theme:
  name: material
  font:
    text: Roboto Condensed
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
  features:
      - content.code.annotate
      - navigation.top
      - navigation.expand
      - toc.integrate
      - content.tabs.link
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/florian-milc/
    - icon: fontawesome/brands/github
      link: https://github.com/florianmilc/rtd-mkdocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
        
nav:
    - Home: index.md
    - Related Information: related_info.md
    - Setting Up the Website:
      - Creating Read the Docs Configuration File: setting_up/creating_rdt.md
      - Adding Configuration Requirements: setting_up/adding_reqs.md
      - Creating MkDocs Configuration File: setting_up/creating_mkd.md
      - Adding Content Files: setting_up/adding_index.md
      - Verifying Project Files: setting_up/project_files.md
    - Launching the Website Locally:
      - Installing MkDocs: launching_locally/install_mkd.md
      - Launching the Website Locally: launching_locally/mkd_serve.md
    - Publishing the Website:
      - Creating Account on Read the Docs: publishing/rtd_signup.md
      - Importing Project Files: publishing/rtd_import_project.md
      - Publishing the Website: publishing/rtd_publish.md
    
