copyright: Copyright &copy; 2022 Florian Milc
site_name: My First Doc Website
nav:
    - Home: index.md
    - Setting Up the Website:
      - Creating Read the Docs Configuration File: creating_rdt.md
      - Adding Configuration Requirements: adding_reqs.md
      - Creating MkDocs Configuration File: creating_mkd.md
      - Adding Content Files: adding_index.md
      - Verifying Project Files: project_files.md
    - Launching the Website Locally:
      - Installing MkDocs: install_mkd.md
      - Launching the Website Locally: mkd_serve.md
theme:
  name: material
  font:
    text: Roboto Condensed
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Whie Mode
  features:
      - content.code.annotate
      - navigation.top
      - navigation.expand
      - toc.integrate
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/florian-milc/
    - icon: fontawesome/brands/github
      link: https://github.com/florianmilc/rtd-mkdocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences